### ISSUE TITLE
Błąd z konsoli wersja spigot 1.8.7 :D

### ISSUE THREAD

**Issue by ToMatch** [grzegorz2047/OpenGuild2047#124]
Jak wiesz wyszła wersja spigot 1.8.7 i właśnie mam taki kaprys że gracze chcą być na bierząco na prywatnym serwerze. Najnowsze wersje WE i WG

{\rtf1\ansi\ansicpg1250\deff0\deflang1045{\fonttbl{\f0\fnil\fcharset238{\*\fname Arial;}Arial CE;}}
{\colortbl ;\red0\green0\blue255;\red255\green0\blue0;}
\viewkind4\uc1\pard\cf1\f0\fs18 20:11:48 [SEVERE] Could not pass event GuildCreateEvent to OpenGuild2047 v0.6.5\par
20:11:48 org.bukkit.event.EventException\par
\cf2 20:11:48 \tab at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d0ae89-a03743b]\par
20:11:48 \tab at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d0ae89-a03743b]\par
20:11:48 \tab at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d0ae89-a03743b]\par
20:11:48 \tab at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d0ae89-a03743b]\par
20:11:48 \tab at pl.grzegorz2047.openguild2047.commands.guild.GuildCreateCommand.execute(GuildCreateCommand.java:100) [OpenGuild2047.jar:?]\par
20:11:49 \tab at pl.grzegorz2047.openguild2047.commands.GuildCommand.onCommand(GuildCommand.java:96) [OpenGuild2047.jar:?]\par
20:11:49 \tab at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d0ae89-a03743b]\par
20:11:49 \tab at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d0ae89-a03743b]\par
20:11:49 \tab at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d0ae89-a03743b]\par
20:11:49 \tab at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d0ae89-a03743b]\par
20:11:49 \tab at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d0ae89-a03743b]\par
20:11:49 \tab at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d0ae89-a03743b]\par
20:11:49 \tab at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d0ae89-a03743b]\par
\cf1 20:11:49 \tab at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d0ae89-a03743b]\par
\cf2 20:11:49 \tab at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]\par
20:11:49 \tab at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]\par
20:11:49 \tab at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d0ae89-a03743b]\par
20:11:49 \tab at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d0ae89-a03743b]\par
20:11:49 \tab at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d0ae89-a03743b]\par
20:11:49 \tab at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d0ae89-a03743b]\par
20:11:49 \tab at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d0ae89-a03743b]\par
20:11:49 \tab at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]\par
20:11:49 Caused by: java.lang.NullPointerException\par
20:11:49 \tab at pl.grzegorz2047.openguild2047.modules.spawn.SpawnChecker.isSpawnExtra(SpawnChecker.java:44) ~[?:?]\par
20:11:49 \tab at pl.grzegorz2047.openguild2047.modules.spawn.SpawnListeners.onGuildCreate(SpawnListeners.java:35) ~[?:?]\par
\cf1 20:11:49 \tab at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]\par
20:11:49 \tab at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]\par
20:11:49 \tab at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]\par
\cf2 20:11:49 \tab at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]\par
20:11:49 \tab at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d0ae89-a03743b]\par
\cf1 20:11:49 \tab ... 21 more}

**Comment by grzegorz2047** [comment]
Oj stary, nie wiem czy zdołam coś ogarnąć xd Dawno nie majstrowałem nad tym.  Nawet nie wiem jaką masz wersję pluginu xd

**Comment by ToMatch** [comment]
@grzegorz2047 Najnowszą wersje. Wiesz liczę na Ciebię :D

**Comment by TheMolkaPL** [comment]
Błąd wystąpił [tu](https://github.com/grzegorz2047/OpenGuild2047/blob/master/src/main/java/pl/grzegorz2047/openguild2047/modules/spawn/SpawnChecker.java#L44).

Skonfiguruj prawidłowo moduł spawn. https://github.com/grzegorz2047/OpenGuild2047/wiki/Modu%C5%82-Spawn

@grzegorz2047 mam (`ts,shootgame.net`), ale obecnie przez miesiąc nie mam możliwości wejścia na niego.
