### ISSUE TITLE
Plugin będzie aktualizowany?

### ISSUE THREAD

**Issue by SlimaKCoder** [grzegorz2047/OpenGuild2047#125]
Tak jak w tytule. Czy będziecie wznawiać pracę nad tym projektem?

**Comment by TheMolkaPL** [comment]
Z mojej strony raczej nie. Jest to kilka powodów.

* Jest już wiele pluginów na gildię (przykładowo [FunnyGuilds](https://github.com/Dzikoysk/FunnyGuilds)), które mają większe możliwości od tego.
* Społeczność Minecraft... Polska scena Minecraft do społeczność poniżej 14 roku życia grająca na pirackiej grze oraz wyzywająca wszystkich gdziekolwiek robiąc przy tym masę błędów ortograficznych.
* Ciężko wprowadzić do plugin coś co zachęciłoby techników (o ile osoby z pytaniami `jak skonfigurować plugin X` lub `jak wgrać plugin X` można nazwać technikami) do jego instalacji.

**Comment by grzegorz2047** [comment]
Ogólnie to piszę następce OpenGuilda.. A jako, że piszę go bardziej pod serwerownie to będzie miał te funkcje, które będą przydatne serwerowni. Coś na pewno z tego będzie i na pewno nie będzie to zbugowane xd No i będzie miało wsparcie co najmniej  tak długo, aż serwerownia nie przestanie z niego korzystać.
